# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='bisw',
    version='0.1.0',
    description='Bilingual Subword Segmentation for Neural Machine Translation (Deguchi et al., 2020)',
    python_requires='==3.*,>=3.7.0',
    author='Hiroyuki Deguchi',
    author_email='deguchi@ai.cs.ehime-u.ac.jp',
    license='MIT',
    entry_points={
        "console_scripts": [
            "bisw-parallel-sents-segmentation = bisw.for_parallel_sents.segmentation:cli_main",
            "bisw-input-sents-preprocess = bisw.for_input_sents.preprocess:cli_main",
            "bisw-input-sents-segmentation = bisw.for_input_sents.segmentation:cli_main"
        ]
    },
    packages=[
        'bisw', 'bisw.for_input_sents.segmenter', 'bisw.for_parallel_sents'
    ],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'fairseq==0.*,>=0.10.1', 'numpy==1.*,>=1.19.4',
        'sentencepiece==0.*,>=0.1.94', 'torch==1.*,>=1.6.0'
    ],
)
